plugins {
	id 'net.fabricmc.fabric-loom'
}

loom {

	accessWidenerPath = project(":common").file("src/main/resources/${project.mod_id}.accesswidener")

	mixin {
		useLegacyMixinAp = false
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	compileOnly "net.fabricmc:sponge-mixin:0.17.0+mixin.0.8.7"
	compileOnly "io.github.llamalad7:mixinextras-fabric:0.5.0"

	// TODO until JEI releases on 26.1
	compileOnly "mezz.jei:jei-1.21.11-common-api:27.4.0.15"

	implementation("dev.ftb.mods:ftb-library:${rootProject.ftb_library_version}")
}

test {
	useJUnitPlatform()
}

publishing {
	publications {
		mavenCommon(MavenPublication) {
			artifactId = "${rootProject.archives_base_name}"
			version ftbPublishing.mavenVersion
			from components.java
		}
	}
}
