modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://go.ftb.team/support-mod-issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbfiltersystem"
version = "${version}"
displayName = "FTB Filter System"
authors = "FTB Team"
description = '''
Smart and highly configurable item filtering system with useful GUI configuration
'''
#logoFile = ""

[[dependencies.ftbfiltersystem]]
modId = "neoforge"
mandatory = true
versionRange = "[20.4.20-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbfiltersystem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbfiltersystem]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.8,)"
ordering = "AFTER"
side = "BOTH"